"""
db.py — persistence for client profiles, measurements, reports, invites and intakes.

Runs on either of two backends, chosen by one environment variable:

    DATABASE_URL unset  → SQLite, one file. Local development and the test suite.
    DATABASE_URL set    → PostgreSQL. What production uses.

Why both, when one is simpler: the tests are the reason. 240 of them run with no
setup beyond a temp file, and that stays true — you can clone this repo and run
the suite without installing a database. Production needs Postgres for a reason
that has nothing to do with SQL: the app is deployed on a host with an ephemeral
disk, so a SQLite file is deleted on every redeploy. That was fine when this was
a demo. It is not fine now that it holds real people's health records.

The risk of two backends is that they drift, and the tests only ever prove one of
them. That's handled by keeping the difference tiny and in one place — the
`_Conn` wrapper and the two `_ID`/`_REAL` type strings below are the whole of it.
Every query in this file is written once, in one dialect. Run the suite against
Postgres before trusting a release:

    DATABASE_URL="postgresql://..." .venv/bin/python -m pytest

Six tables:
    clients       one row per person the coach tracks
    measurements  many rows per client, one per weigh-in — this is the time series
    reports       saved assessment snapshots, stored as JSON
    invites       one-time onboarding links, each with an unguessable token
    intakes       submitted onboarding questionnaires, stored as JSON
    sessions      coach logins, stored as a hash of the token — see security.py

`reports` stores the whole response as a JSON blob rather than normalising it
into columns. That's deliberate: the report shape includes long-form explanation
text and will keep evolving as the knowledge base grows, and a snapshot should
stay exactly as it was when the coach handed it to the client — including the
wording of the advice. Normalising it would break that guarantee on every schema
change.

Timestamps are stored as TEXT in ISO-8601 on both backends, not as a native
timestamp type. That's deliberate too: it means `datetime.fromisoformat()` reads
back exactly what was written, on either backend, with no driver doing timezone
conversion in between. Health records should not change meaning because of a
driver upgrade.
"""

from __future__ import annotations

import json
import os
import secrets
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
USE_POSTGRES = DATABASE_URL.startswith(("postgres://", "postgresql://"))

DB_PATH = os.environ.get(
    "TOOLKIT_DB",
    os.path.join(os.path.dirname(__file__), "..", "toolkit.db"),
)

# ---------------------------------------------------------------------------
#  The entire dialect difference
# ---------------------------------------------------------------------------
#
# An auto-incrementing primary key and a 64-bit float are spelled differently in
# the two engines. Postgres's REAL is 4-byte; SQLite's is 8-byte, so it maps to
# DOUBLE PRECISION rather than REAL — otherwise a bodyweight would quietly lose
# precision on one backend and not the other.

_ID = ("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if USE_POSTGRES
       else "INTEGER PRIMARY KEY AUTOINCREMENT")
_REAL = "DOUBLE PRECISION" if USE_POSTGRES else "REAL"

# Statements are a list, not one script, because Postgres's driver sends one
# statement per round trip. Keeping them separate means both backends run the
# identical list and neither needs a fragile split-on-semicolon.
SCHEMA: tuple[str, ...] = (
    f"""
    CREATE TABLE IF NOT EXISTS clients (
      id          {_ID},
      name        TEXT NOT NULL,
      sex         TEXT NOT NULL,
      age         INTEGER,
      height_cm   {_REAL},
      diet        TEXT,
      goal        TEXT,
      notes       TEXT,
      created_at  TEXT
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS measurements (
      id          {_ID},
      client_id   INTEGER NOT NULL,
      taken_on    TEXT NOT NULL,
      weight_kg   {_REAL},
      bodyfat_pct {_REAL},
      waist_cm    {_REAL},
      neck_cm     {_REAL},
      hip_cm      {_REAL},
      chest_cm    {_REAL},
      arm_cm      {_REAL},
      thigh_cm    {_REAL},
      note        TEXT,
      created_at  TEXT,
      FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS reports (
      id          {_ID},
      client_id   INTEGER,
      created_at  TEXT,
      goal        TEXT,
      kcal        INTEGER,
      payload     TEXT,
      FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
    )""",
    # One-time onboarding links. A client gets an unguessable token rather than a
    # public form, so an intake URL can't be found by guessing and can't be reused
    # or passed around after it's been filled in.
    f"""
    CREATE TABLE IF NOT EXISTS invites (
      id           {_ID},
      token        TEXT UNIQUE NOT NULL,
      label        TEXT,
      created_at   TEXT,
      expires_at   TEXT,
      submitted_at TEXT,
      revoked_at   TEXT
    )""",
    # Submitted questionnaires. `payload` holds the answers as JSON for the same
    # reason `reports` does: it's a long questionnaire that will keep evolving, and
    # a submission should stay exactly as the client wrote it even after the
    # questions change. name and contact are lifted out as columns purely so the
    # coach's list view doesn't have to parse every payload to render.
    f"""
    CREATE TABLE IF NOT EXISTS intakes (
      id              {_ID},
      invite_id       INTEGER,
      client_id       INTEGER,
      created_at      TEXT,
      consent_version TEXT,
      consent_at      TEXT,
      full_name       TEXT,
      contact         TEXT,
      payload         TEXT,
      FOREIGN KEY (invite_id) REFERENCES invites(id) ON DELETE SET NULL,
      FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL
    )""",
    # Coach sessions. Stored because the host sleeps after ~15 idle minutes and
    # in-memory sessions died with the process — meaning the coach was logged out
    # almost every time they opened the app.
    #
    # The primary key is a SHA-256 of the token, never the token. A session
    # cookie is a live credential: anyone reading this table from a backup or a
    # console would otherwise be able to log in as the coach. Hashes can't be
    # replayed, and the lookup works exactly the same because the app hashes the
    # cookie it was given and looks for that.
    """
    CREATE TABLE IF NOT EXISTS sessions (
      token_hash TEXT PRIMARY KEY,
      created_at TEXT,
      expires_at TEXT
    )""",
    # The measurements query is always "everything for one client, in date order",
    # so index exactly that.
    "CREATE INDEX IF NOT EXISTS idx_measurements_client ON measurements(client_id, taken_on)",
    "CREATE INDEX IF NOT EXISTS idx_reports_client ON reports(client_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_invites_token ON invites(token)",
    "CREATE INDEX IF NOT EXISTS idx_intakes_created ON intakes(created_at)",
)

# Every table the app expects. _ensure_schema compares against this rather than
# checking one table, so adding a table to SCHEMA above is enough to have it
# created on databases that already exist.
EXPECTED_TABLES = {"clients", "measurements", "reports", "invites", "intakes",
                   "sessions"}

MEASUREMENT_COLS = [
    "taken_on", "weight_kg", "bodyfat_pct", "waist_cm", "neck_cm",
    "hip_cm", "chest_cm", "arm_cm", "thigh_cm", "note",
]

CLIENT_COLS = ["name", "sex", "age", "height_cm", "diet", "goal", "notes"]

_TABLE_QUERY = (
    "SELECT table_name AS name FROM information_schema.tables "
    "WHERE table_schema = current_schema()" if USE_POSTGRES
    else "SELECT name FROM sqlite_master WHERE type='table'"
)


# ---------------------------------------------------------------------------
#  Connection wrapper
# ---------------------------------------------------------------------------

class _Conn:
    """
    The four operations this app performs, spelled the same way on both backends.

    Call sites use `query` / `query_one` / `run` / `insert` and never touch a
    cursor, a row factory or a placeholder style. That's what keeps the dialect
    difference confined to this class instead of spreading across 40 call sites.

    SQL is written once, with `?` placeholders. Postgres wants `%s`, so `insert`
    and friends translate on the way through. No query in this module contains a
    literal `?` inside a string, which is what makes that substitution safe — if
    you ever add one, parameterise it instead.
    """

    __slots__ = ("_c",)

    def __init__(self, conn):
        self._c = conn

    @staticmethod
    def _sql(sql: str) -> str:
        return sql.replace("?", "%s") if USE_POSTGRES else sql

    def query(self, sql: str, params=()) -> list[dict]:
        cur = self._c.execute(self._sql(sql), tuple(params))
        return [dict(r) for r in cur.fetchall()]

    def query_one(self, sql: str, params=()) -> dict | None:
        cur = self._c.execute(self._sql(sql), tuple(params))
        row = cur.fetchone()
        return dict(row) if row else None

    def run(self, sql: str, params=()) -> int:
        """Execute a write. Returns the number of rows affected."""
        cur = self._c.execute(self._sql(sql), tuple(params))
        return cur.rowcount

    def insert(self, sql: str, params=()) -> int:
        """
        Execute an INSERT and return the new row's id.

        SQLite hands it back on the cursor. Postgres has no equivalent, so the
        statement gets a RETURNING clause — which is also the only correct way to
        do this under a connection pool, where "the last id on this connection"
        would be a race waiting to happen.
        """
        if USE_POSTGRES:
            cur = self._c.execute(self._sql(sql) + " RETURNING id", tuple(params))
            return cur.fetchone()["id"]
        return self._c.execute(sql, tuple(params)).lastrowid

    def ddl(self, sql: str) -> None:
        self._c.execute(sql)


def _ensure_schema(c: _Conn) -> None:
    """
    Create the schema if it isn't there.

    Called on every connection, which sounds wasteful but isn't: it's one catalogue
    lookup, and this app serves a handful of requests per session.

    It exists because `init_db()` at startup is not enough. SQLite is a plain
    file, so it can disappear under a running process — deleted during a tidy-up,
    moved, restored from a backup, or TOOLKIT_DB repointed at a fresh path. When
    that happened, `sqlite3.connect()` happily created a new empty file and every
    query then failed with "no such table: clients" as an opaque 500. The endpoint
    looked broken when the real problem was a missing file.

    It matters just as much on Postgres, for a different reason: a fresh Neon
    database starts empty, and a restore to a point in time before a table existed
    leaves the app pointing at a database missing that table.

    CREATE TABLE IF NOT EXISTS makes this idempotent, so recovery costs nothing
    and needs no restart.

    It also doubles as the migration path. Checking one table wasn't enough: when
    `invites` and `intakes` were added, an existing database already had `clients`,
    so a single-table check would have passed and the new tables would never have
    been created. Comparing the full expected set means adding a table to SCHEMA
    is all that's needed.
    """
    present = {r["name"] for r in c.query(_TABLE_QUERY)}
    if not EXPECTED_TABLES.issubset(present):
        for stmt in SCHEMA:
            c.ddl(stmt)


# Postgres checks the schema once per process rather than once per connection.
# The self-healing argument above is about a *file* vanishing under a running
# process, which is a SQLite property; a managed Postgres database does not
# disappear between two requests. Over the network that check would be an extra
# round trip on every single query — slower for the coach, and it spends the free
# tier's compute allowance on asking a question whose answer never changes.
_pg_schema_checked = False


# --- Postgres connection pool ----------------------------------------------
#
# min_size=0 is not a detail, it's the whole reason this stays free. Neon
# suspends the compute after five minutes with no connections, and suspended
# time costs nothing against the monthly compute allowance. A pool that kept one
# connection warm would hold the database awake around the clock and burn the
# free tier in about four days.

_pool = None


def _get_pool():
    global _pool
    if _pool is None:
        from psycopg_pool import ConnectionPool
        from psycopg.rows import dict_row

        _pool = ConnectionPool(
            DATABASE_URL,
            min_size=0,
            max_size=4,          # one worker, a handful of clients
            max_idle=30,         # let Neon go back to sleep promptly
            kwargs={"row_factory": dict_row},
            open=True,
        )
    return _pool


@contextmanager
def db():
    """Short-lived connection, schema-checked, committed on clean exit."""
    if USE_POSTGRES:
        global _pg_schema_checked
        with _get_pool().connection() as conn:
            # psycopg commits on clean exit and rolls back on exception, which is
            # the same contract the SQLite branch below provides.
            c = _Conn(conn)
            if not _pg_schema_checked:
                _ensure_schema(c)
                _pg_schema_checked = True
            yield c
        return

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    # SQLite has foreign keys off by default, per connection — so ON DELETE
    # CASCADE only works if we turn it on every time. Postgres enforces them
    # always and needs no equivalent.
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        c = _Conn(conn)
        _ensure_schema(c)
        yield c
        conn.commit()
    finally:
        conn.close()


_last_error: str | None = None


def init_db() -> None:
    """
    Create the schema at startup, and do not die if that fails.

    It used to raise, which was right when the database was a local file: if you
    can't write the file, nothing works, so failing loudly at boot was the honest
    signal. Over a network it's the wrong trade. Neon suspends after five minutes
    idle, so a redeploy can easily land while the database is asleep or briefly
    unreachable — and raising here would abort startup and take down the public
    calculator, which needs no database at all.

    So: try, remember what went wrong, and let the app boot. The calculator keeps
    serving, `db()` retries on the next request and self-heals, and /api/health
    reports the failure so a genuinely broken DATABASE_URL is still one curl away
    from being caught rather than silently degraded.
    """
    global _last_error
    try:
        with db() as c:
            _ensure_schema(c)
        _last_error = None
    except Exception as e:                        # noqa: BLE001 — surfaced, not swallowed
        _last_error = f"{type(e).__name__}: {e}"


def backend() -> str:
    """Which store is live. Surfaced on /api/health so a misconfigured deploy is visible."""
    return "postgres" if USE_POSTGRES else "sqlite"


def health() -> dict:
    """
    Can we actually reach the store right now?

    Deliberately performs a real round trip rather than reporting a cached flag —
    "the pool exists" is not the same claim as "your clients' records are
    reachable", and only the second one is worth putting on a health endpoint.
    """
    global _last_error
    try:
        with db() as c:
            c.query("SELECT 1 AS ok")
        _last_error = None
        return {"backend": backend(), "reachable": True, "error": None}
    except Exception as e:                        # noqa: BLE001
        _last_error = f"{type(e).__name__}: {e}"
        return {"backend": backend(), "reachable": False, "error": _last_error}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


# ---------------------------------------------------------------------------
#  Clients
# ---------------------------------------------------------------------------

def create_client(data: dict) -> dict:
    with db() as c:
        new_id = c.insert(
            f"INSERT INTO clients ({', '.join(CLIENT_COLS)}, created_at) "
            f"VALUES ({', '.join('?' * len(CLIENT_COLS))}, ?)",
            [data.get(k) for k in CLIENT_COLS] + [_now()],
        )

    # Deliberately OUTSIDE the `with` block. get_client() takes its own
    # connection, and the INSERT above is only committed when the block exits —
    # so calling it inside would query a connection that cannot see the new row
    # yet and would return None.
    return get_client(new_id)


def list_clients() -> list[dict]:
    """All clients, newest first, each with a measurement count for the list UI."""
    with db() as c:
        return c.query("""
            SELECT c.*,
                   (SELECT COUNT(*) FROM measurements m WHERE m.client_id = c.id)
                       AS measurement_count,
                   (SELECT MAX(taken_on) FROM measurements m WHERE m.client_id = c.id)
                       AS last_measured
            FROM clients c
            ORDER BY c.id DESC
        """)


def get_client(client_id: int) -> dict | None:
    with db() as c:
        return c.query_one("SELECT * FROM clients WHERE id = ?", (client_id,))


def update_client(client_id: int, data: dict) -> dict | None:
    if not get_client(client_id):
        return None
    with db() as c:
        c.run(
            f"UPDATE clients SET {', '.join(f'{k} = ?' for k in CLIENT_COLS)} "
            "WHERE id = ?",
            [data.get(k) for k in CLIENT_COLS] + [client_id],
        )
    return get_client(client_id)


def delete_client(client_id: int) -> bool:
    """Deletes the client and — via ON DELETE CASCADE — their measurements and reports."""
    with db() as c:
        return c.run("DELETE FROM clients WHERE id = ?", (client_id,)) > 0


# ---------------------------------------------------------------------------
#  Measurements
# ---------------------------------------------------------------------------

def add_measurement(client_id: int, data: dict) -> dict:
    with db() as c:
        new_id = c.insert(
            f"INSERT INTO measurements (client_id, {', '.join(MEASUREMENT_COLS)}, created_at) "
            f"VALUES (?, {', '.join('?' * len(MEASUREMENT_COLS))}, ?)",
            [client_id] + [data.get(k) for k in MEASUREMENT_COLS] + [_now()],
        )
        return c.query_one("SELECT * FROM measurements WHERE id = ?", (new_id,))


def list_measurements(client_id: int) -> list[dict]:
    """Chronological — the charts plot straight from this order."""
    with db() as c:
        return c.query(
            "SELECT * FROM measurements WHERE client_id = ? ORDER BY taken_on ASC, id ASC",
            (client_id,),
        )


def delete_measurement(measurement_id: int) -> bool:
    with db() as c:
        return c.run("DELETE FROM measurements WHERE id = ?", (measurement_id,)) > 0


def progress_summary(client_id: int) -> dict | None:
    """
    First vs latest measurement, and the change between them.

    Returned separately from the raw list because it's what a coach actually
    opens the app to see: "is this working?"
    """
    rows = list_measurements(client_id)
    if not rows:
        return None
    first, last = rows[0], rows[-1]

    def delta(key: str):
        a, b = first.get(key), last.get(key)
        return round(b - a, 1) if a is not None and b is not None else None

    # Fat and lean mass change is the interesting part — losing 5 kg means very
    # different things depending on what it was made of.
    fat_change = lean_change = None
    if first.get("bodyfat_pct") and last.get("bodyfat_pct"):
        f_first = first["weight_kg"] * first["bodyfat_pct"] / 100
        f_last = last["weight_kg"] * last["bodyfat_pct"] / 100
        fat_change = round(f_last - f_first, 1)
        lean_change = round(
            (last["weight_kg"] - f_last) - (first["weight_kg"] - f_first), 1
        )

    return {
        "entries": len(rows),
        "first": first,
        "latest": last,
        "weight_change_kg": delta("weight_kg"),
        "bodyfat_change_pct": delta("bodyfat_pct"),
        "waist_change_cm": delta("waist_cm"),
        "fat_mass_change_kg": fat_change,
        "lean_mass_change_kg": lean_change,
    }


# ---------------------------------------------------------------------------
#  Saved reports
# ---------------------------------------------------------------------------

def save_report(client_id: int | None, report: dict) -> dict:
    """Snapshot a full assessment, stored as JSON. See the module docstring for why."""
    with db() as c:
        new_id = c.insert(
            "INSERT INTO reports (client_id, created_at, goal, kcal, payload) "
            "VALUES (?, ?, ?, ?, ?)",
            (
                client_id,
                _now(),
                report.get("input", {}).get("goal"),
                report.get("nutrition", {}).get("kcal", {}).get("number"),
                json.dumps(report),
            ),
        )
        return {"id": new_id, "created_at": _now()}


def list_reports(client_id: int | None = None) -> list[dict]:
    """Report index — metadata only, no payload, so the list stays light."""
    with db() as c:
        if client_id is None:
            return c.query(
                "SELECT id, client_id, created_at, goal, kcal FROM reports "
                "ORDER BY id DESC LIMIT 100"
            )
        return c.query(
            "SELECT id, client_id, created_at, goal, kcal FROM reports "
            "WHERE client_id = ? ORDER BY id DESC",
            (client_id,),
        )


def get_report(report_id: int) -> dict | None:
    with db() as c:
        d = c.query_one("SELECT * FROM reports WHERE id = ?", (report_id,))
        if not d:
            return None
        d["payload"] = json.loads(d["payload"])
        return d


def delete_report(report_id: int) -> bool:
    with db() as c:
        return c.run("DELETE FROM reports WHERE id = ?", (report_id,)) > 0


# ---------------------------------------------------------------------------
#  Onboarding invites
# ---------------------------------------------------------------------------

INVITE_TTL_DAYS = 14


def create_invite(label: str | None, ttl_days: int = INVITE_TTL_DAYS) -> dict:
    """
    Mint a one-time onboarding link.

    The token is 32 URL-safe bytes from `secrets`, so it can't be guessed or
    enumerated — that's what makes a private form private without a login for the
    client. It expires so an old link in someone's WhatsApp history stops working.
    """
    token = secrets.token_urlsafe(32)
    now = datetime.now(timezone.utc)
    expires = now + timedelta(days=max(1, min(90, ttl_days)))

    with db() as c:
        new_id = c.insert(
            "INSERT INTO invites (token, label, created_at, expires_at) VALUES (?, ?, ?, ?)",
            (token, label, now.isoformat(timespec="seconds"),
             expires.isoformat(timespec="seconds")),
        )
    return get_invite(new_id)


def get_invite(invite_id: int) -> dict | None:
    with db() as c:
        return c.query_one("SELECT * FROM invites WHERE id = ?", (invite_id,))


def get_invite_by_token(token: str) -> dict | None:
    with db() as c:
        return c.query_one("SELECT * FROM invites WHERE token = ?", (token,))


def invite_state(invite: dict | None) -> str:
    """
    Why a link can't be used — so the client sees a clear reason rather than a 404.

    Returns: "ok" | "missing" | "revoked" | "used" | "expired"
    """
    if not invite:
        return "missing"
    if invite.get("revoked_at"):
        return "revoked"
    if invite.get("submitted_at"):
        return "used"
    try:
        if datetime.fromisoformat(invite["expires_at"]) < datetime.now(timezone.utc):
            return "expired"
    except (TypeError, ValueError):
        pass
    return "ok"


def list_invites() -> list[dict]:
    """Newest first, with a usable/used state for each."""
    with db() as c:
        rows = c.query("SELECT * FROM invites ORDER BY id DESC LIMIT 200")
    for d in rows:
        d["state"] = invite_state(d)
    return rows


def revoke_invite(invite_id: int) -> bool:
    with db() as c:
        return c.run(
            "UPDATE invites SET revoked_at = ? WHERE id = ? AND revoked_at IS NULL",
            (_now(), invite_id),
        ) > 0


def delete_invite(invite_id: int) -> bool:
    with db() as c:
        return c.run("DELETE FROM invites WHERE id = ?", (invite_id,)) > 0


# ---------------------------------------------------------------------------
#  Submitted intakes
# ---------------------------------------------------------------------------

def create_intake(*, invite_id: int, answers: dict, consent_version: str) -> dict:
    """
    Store a submission and burn the invite in the same transaction.

    Both happen on one connection so a link can't be marked used while its
    answers fail to save, or vice versa — the client would either lose their work
    or be able to submit twice.
    """
    now = _now()
    with db() as c:
        new_id = c.insert(
            "INSERT INTO intakes (invite_id, created_at, consent_version, consent_at, "
            "full_name, contact, payload) VALUES (?, ?, ?, ?, ?, ?, ?)",
            (invite_id, now, consent_version, now,
             (answers.get("full_name") or "").strip() or None,
             (answers.get("contact") or "").strip() or None,
             json.dumps(answers)),
        )
        c.run("UPDATE invites SET submitted_at = ? WHERE id = ?", (now, invite_id))
    return {"id": new_id, "created_at": now}


def list_intakes() -> list[dict]:
    """Index for the coach's list — no payload, so it stays light."""
    with db() as c:
        return c.query(
            "SELECT id, invite_id, client_id, created_at, full_name, contact "
            "FROM intakes ORDER BY id DESC LIMIT 200"
        )


def get_intake(intake_id: int) -> dict | None:
    with db() as c:
        d = c.query_one("SELECT * FROM intakes WHERE id = ?", (intake_id,))
        if not d:
            return None
        d["answers"] = json.loads(d.pop("payload") or "{}")
        return d


def delete_intake(intake_id: int) -> bool:
    """
    Hard delete, for a client exercising their right to have data removed.

    A soft delete would leave their health answers sitting in the database, which
    would make the promise on the consent screen untrue.
    """
    with db() as c:
        return c.run("DELETE FROM intakes WHERE id = ?", (intake_id,)) > 0


def link_intake_to_client(intake_id: int, client_id: int) -> bool:
    with db() as c:
        return c.run(
            "UPDATE intakes SET client_id = ? WHERE id = ?", (client_id, intake_id)
        ) > 0


# ---------------------------------------------------------------------------
#  Coach sessions
# ---------------------------------------------------------------------------
#
# Only ever handed a hash — see the sessions table comment in SCHEMA. This layer
# deliberately knows nothing about tokens, cookies or expiry policy; that stays
# in security.py, which is where someone reviewing the auth boundary will look.
#
# Expiry is compared as text. Every timestamp this module writes is UTC
# ISO-8601 from _now(), so the strings sort in the same order as the instants
# they represent — the comparison is only sound because the format is uniform.

def session_create(token_hash: str, expires_at: str) -> None:
    with db() as c:
        c.run(
            "INSERT INTO sessions (token_hash, created_at, expires_at) VALUES (?, ?, ?)",
            (token_hash, _now(), expires_at),
        )


def session_live(token_hash: str) -> bool:
    """True only if this session exists and has not expired."""
    with db() as c:
        row = c.query_one(
            "SELECT 1 AS ok FROM sessions WHERE token_hash = ? AND expires_at > ?",
            (token_hash, _now()),
        )
    return row is not None


def session_delete(token_hash: str) -> None:
    with db() as c:
        c.run("DELETE FROM sessions WHERE token_hash = ?", (token_hash,))


def session_prune() -> None:
    """Drop expired rows. Called on login, not on every request — it's housekeeping."""
    with db() as c:
        c.run("DELETE FROM sessions WHERE expires_at <= ?", (_now(),))
